language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - STORAGE=doctrine
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 5.6
      env:
        - STORAGE=doctrine
    - php: 5.6
      env:
        - STORAGE=array
    - php: 7.0
      env:
        - STORAGE=doctrine
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
      env:
        - STORAGE=doctrine
    - php: 7.0
      env:
        - STORAGE=array
    - php: 7.0
      env:
        - STORAGE=doctrine
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
      env:
        - STORAGE=doctrine
    - php: 7.1
      env:
        - STORAGE=array
    - php: 7.1
      env:
        - STORAGE=doctrine
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.1
      env:
        - STORAGE=doctrine
        - CODE_COVERAGE="--coverage-clover=coverage.clover"
    - php: 7.2
      env:
        - STORAGE=array
    - php: 7.2
      env:
        - STORAGE=doctrine
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.2
      env:
        - STORAGE=doctrine
    - php: 7.3
      env:
        - STORAGE=array
    - php: 7.3
      env:
        - STORAGE=doctrine
    - php: 7.4
      env:
        - STORAGE=array
    - php: 7.4
      env:
        - STORAGE=doctrine

before_install:
  - if [[ -z $CODE_COVERAGE ]]; then phpenv config-rm xdebug.ini ; fi
  - phpenv config-add tests/travis.php.ini

install:
   - composer update $COMPOSER_FLAGS
   - composer info

before_script:
  - if [[ $STORAGE == 'doctrine' ]]; then tests/app/console doctrine:database:create ; fi
  - if [[ $STORAGE == 'doctrine' ]]; then tests/app/console doctrine:schema:create ; fi

script:
   - vendor/bin/phpunit -c phpunit.xml.dist $CODE_COVERAGE

after_script:
  - if [[ -n $CODE_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ -n $CODE_COVERAGE ]]; then php ocular.phar code-coverage:upload --access-token="230ec5e01daf5bb3e46ea304fb20348b52d80de73463ec08ee9c96fcd1349e35" --format=php-clover coverage.clover ; fi

cache:
  directories:
    - "$HOME/.composer/cache"
