language: php

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - STORAGE=array
  - STORAGE=doctrine

install:
   - composer self-update
   - composer update
   - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - mysql -e 'create database task_test;'

script:
   - phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --access-token="230ec5e01daf5bb3e46ea304fb20348b52d80de73463ec08ee9c96fcd1349e35" --format=php-clover coverage.clover
